node{

  git branch: "master", url: "https://github.com/robsonbittencourt/jenkins-pipeline-example" 

  stage('Unit Tests') {
    withEnv(["JAVA_HOME=${ tool "java-11" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn test"
    }
  }

  stage ('Sonarqube') {
    withEnv(["JAVA_HOME=${ tool "java-11" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn sonar:sonar -Dsonar.host.url=http://sonar:9000"
    }
  }

  stage ('Build Jar') {
    withEnv(["JAVA_HOME=${ tool "java-11" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn clean package -Dmaven.test.skip=true"
    }
  }

  stage ('Build and Deploy DSV image') {
    sh "docker build -t localhost:5000/jenkins-pipeline-example:dsv ."
    sh "docker push localhost:5000/jenkins-pipeline-example:dsv"
  }

  stage ('Deploy app in DSV') {
    sh "docker rm -f app-dsv &>/dev/null && sleep 1 && docker run --name=app-dsv -p 8081:8081 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=dsv -d localhost:5000/jenkins-pipeline-example:dsv"
  }

  stage ('Build and Deploy UAT image') {
    sh "docker tag localhost:5000/jenkins-pipeline-example:dsv localhost:5000/jenkins-pipeline-example:uat"
    sh "docker push localhost:5000/jenkins-pipeline-example:uat"
  }

  stage ('Deploy app in UAT') {
    sh "docker rm -f app-uat &>/dev/null && sleep 1 && docker run --name=app-uat -p 8085:8085 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=uat -d localhost:5000/jenkins-pipeline-example:uat"
  }

  stage ('UI Tests') {
    withEnv(["JAVA_HOME=${ tool "java-11" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "sleep 5"
        sh "mvn verify -Pui-tests"
    }   
  }

  stage ('Build and Deploy PRD image') {
    sh "docker tag localhost:5000/jenkins-pipeline-example:uat localhost:5000/jenkins-pipeline-example:prd"
    sh "docker push localhost:5000/jenkins-pipeline-example:prd"
  }

  stage ('Deploy app in PRD') {
    sh "docker rm -f app-prd &>/dev/null && sleep 1 && docker run --name=app-prd -p 8090:8090 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=prd -d localhost:5000/jenkins-pipeline-example:prd"
  }
stage ('Build and Deploy UAT image') {
    sh "docker tag localhost:5000/jenkins-pipeline-example:dsv localhost:5000/jenkins-pipeline-example:uat"
    sh "docker push localhost:5000/jenkins-pipeline-example:uat"
  }

  stage ('Deploy app in UAT') {
    sh "docker rm -f app-uat &>/dev/null && sleep 1 && docker run --name=app-uat -p 8085:8085 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=uat -d localhost:5000/jenkins-pipeline-example:uat"
  }

  stage ('UI Tests') {
    withEnv(["JAVA_HOME=${ tool "java-11" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "sleep 5"
        sh "mvn verify -Pui-tests"
    }   
  }

  stage ('Build and Deploy PRD image') {
    sh "docker tag localhost:5000/jenkins-pipeline-example:uat localhost:5000/jenkins-pipeline-example:prd"
    sh "docker push localhost:5000/jenkins-pipeline-example:prd"
  }

  stage ('Deploy app in PRD') {
    sh "docker rm -f app-prd &>/dev/null && sleep 1 && docker run --name=app-prd -p 8090:8090 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=prd -d localhost:5000/jenkins-pipeline-example:prd"
  }

  stage ('Build and Deploy UAT image') {
    sh "docker tag localhost:5000/jenkins-pipeline-example:dsv localhost:5000/jenkins-pipeline-example:uat"
    sh "docker push localhost:5000/jenkins-pipeline-example:uat"
  }

  stage ('Deploy app in UAT') {
    sh "docker rm -f app-uat &>/dev/null && sleep 1 && docker run --name=app-uat -p 8085:8085 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=uat -d localhost:5000/jenkins-pipeline-example:uat"
  }

  stage ('UI Tests') {
    withEnv(["JAVA_HOME=${ tool "java-11" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "sleep 5"
        sh "mvn verify -Pui-tests"
    }   
  }

  stage ('Build and Deploy PRD image') {
    sh "docker tag localhost:5000/jenkins-pipeline-example:uat localhost:5000/jenkins-pipeline-example:prd"
    sh "docker push localhost:5000/jenkins-pipeline-example:prd"
  }

  stage ('Deploy app in PRD') {
    sh "docker rm -f app-prd &>/dev/null && sleep 1 && docker run --name=app-prd -p 8090:8090 --net jenkins-pipeline-example_default -e SPRING_PROFILES_ACTIVE=prd -d localhost:5000/jenkins-pipeline-example:prd"
  }

}
